In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load the dataset
file_path = 'C:\\Users\\PC\\Desktop\\procdna\\Final_data.csv'
data = pd.read_csv(file_path)

# Extract the selected columns
selected_columns = [
    'Times Cited, All Databases',
    'Since 2013 Usage Count',
    'Funding_Total',
    'Total Payment',
    'Affiliations_Total',
    'Unique_Affiliations',
    'Research_Areas_unique'
]
data_selected = data[selected_columns].fillna(0)  # Replace NaNs with 0

# Initialize the scaler, MinMaxScaler, to scale the scores between 1 and 100
scaler = MinMaxScaler(feature_range=(1, 100))
data_scaled = scaler.fit_transform(data_selected)

# Convert the scaled data back to a DataFrame
data_scaled_df = pd.DataFrame(data_scaled, columns=selected_columns)

# Compute the weighted average for each author to get the final score
weights = [0.35, 0.05, 0.15, 0.15, 0.10, 0.10, 0.10]
data_scaled_df['Score'] = data_scaled_df.dot(weights)

# Dynamically find the maximum score
max_score = data_scaled_df['Score'].max()

# Normalizing the 'Score' to a 0-100 scale using the dynamically found maximum score
data_scaled_df['Score Normalized'] = (data_scaled_df['Score'] / max_score) * 100

# Adding the author names back for reference
data_scaled_df['Author Full Names'] = data['Author Full Names']

# Sort the DataFrame based on the normalized score in descending order
sorted_scores = data_scaled_df[['Author Full Names', 'Score', 'Score Normalized', 'Times Cited, All Databases', 'Since 2013 Usage Count', 'Funding_Total', 'Total Payment', 'Affiliations_Total', 'Unique_Affiliations', 'Research_Areas_unique']].sort_values(by='Score Normalized', ascending=False)

# Display the top authors and their scores
print(sorted_scores.head(30))

# Save the updated DataFrame to a CSV file
sorted_scores.to_csv('C:\\Users\\PC\\Desktop\\procdna\\sorted_scores_normalized.csv', index=False)

                  Author Full Names      Score  Score Normalized  \
5924                 HANSSON, OSKAR  58.115769        100.000000
1470                   BLENNOW, KAJ  44.970988         77.381730
8646                        LI, MIN  37.839636         65.110790
6929             JANELIDZE, SHORENA  36.995529         63.658332
8985                      LIU, YANG  35.186718         60.545906
517                  ARASAKI, KOHEI  34.583544         59.508021
8695                         LI, Y.  33.177921         57.089360
6495                         HU, J.  33.177921         57.089360
9861      MATTSSON-CARLGREN, NIKLAS  32.196890         55.401298
1077                  BEALE, RUPERT  30.053466         51.713101
2298                 CASTORI, MARCO  30.029760         51.672309
10163               MERLA, GIUSEPPE  30.029760         51.672309
620             ASHTON, NICHOLAS J.  27.755787         47.759476
11476          PALMQVIST, SEBASTIAN  27.153061         46.722364
3034               COOKSON, MARK R.  26.326642         45.300343
7116                JOHANSEN, TERJE  25.735030         44.282353
4353               FANG, EVANDRO F.  25.735030         44.282353
7977                 KROEMER, GUIDO  25.735030         44.282353
5913                 HANSEN, MALENE  25.735030         44.282353
34                    ABEL, STEFFEN  25.691614         44.207647
2323             CAULFIELD, MARK J.  24.852687         42.764103
696                    AYTON, SCOTT  24.569428         42.276697
10959               NETEA, MIHAI G.  24.527551         42.204641
2782               CHU, CHARLEEN T.  24.246976         41.721854
8938                       LIU, JIA  24.042425         41.369881
3635                  DEWSON, GRANT  23.240173         39.989445
5387   GONZALEZ-RODRIGUEZ, PATRICIA  22.893998         39.393779
7746               KLEIN, CHRISTINE  22.885985         39.379993
10232                   MIKI, YASUO  22.486079         38.691872
665                     AUTON, ADAM  22.331312         38.425564

       Times Cited, All Databases  Since 2013 Usage Count  Funding_Total  \
5924                   100.000000               87.802875     100.000000
1470                    67.678891               55.954825      96.255319
8646                    59.355098               88.006160       3.223404
6929                    60.889982               39.149897      71.329787
8985                    54.720930               79.739220       1.936170
517                     27.860465               40.369610       1.468085
8695                    33.350626               16.110883      62.787234
6495                    33.350626               16.110883      62.787234
9861                    52.684258               38.404517      60.446809
1077                    41.084079               53.854209       1.585106
2298                    41.084079               53.854209       1.585106
10163                   41.084079               53.854209       1.585106
620                     40.021467               36.710472      60.212766
11476                   45.452594               27.156057      48.744681
3034                    35.180680               59.749487      15.276596
7116                    39.962433               47.823409       7.436170
4353                    39.962433               47.823409       7.436170
7977                    39.962433               47.823409       7.436170
5913                    39.962433               47.823409       7.436170
34                      27.860465               40.369610       1.468085
2323                    22.134168               30.205339      40.670213
696                     36.302326               55.141684       2.755319
10959                   36.922182               57.987680       4.042553
2782                    37.040250               51.279261       2.638298
8938                    34.678891               58.326489       2.404255
3635                    34.796959               49.381930       3.223404
5387                    34.236136               52.498973       2.170213
7746                    43.386404               96.882957       4.042553
10232                   33.793381               42.266940       1.585106
665                     17.795170               25.123203      37.159574

       Total Payment  Affiliations_Total  Unique_Affiliations  \
5924        1.000000           20.237991             5.652588
1470        1.000000           20.382096             5.770375
8646        1.000000           82.203057            34.157049
6929        1.000000           15.554585             4.828079
8985        1.000000           81.266376            33.803688
517       100.000000           41.133188            33.803688
8695        1.000000          100.000000             7.360500
6495        1.000000          100.000000             7.360500
9861        1.000000           12.744541             3.591315
1077        1.158043           72.043668            51.177275
2298        1.000000           72.043668            51.177275
10163       1.000000           72.043668            51.177275
620         1.383006           13.753275             4.592504
11476       1.000000           11.447598             4.415824
3034        1.000000           45.312227            35.099346
7116        1.000000           42.862445            34.098156
4353        1.000000           42.862445            34.098156
7977        1.000000           42.862445            34.098156
5913        1.000000           42.862445            34.098156
34         40.720467           41.133188            33.803688
2323        1.000000           55.759825            36.689471
696         1.011969           45.888646            35.570494
10959       1.000000           42.502183            34.510410
2782        1.000000           42.141921            34.157049
8938        1.000000           41.997817            34.392623
3635        1.000000           41.709607            33.921475
5387        1.000000           41.709607            33.921475
7746        1.000000           10.510917             6.535990
10232       1.000000           44.231441            34.863772
665         1.048187           53.526201            36.630577

       Research_Areas_unique
5924                9.865672
1470               12.820896
8646                3.955224
6929                8.388060
8985                1.000000
517                 1.000000
8695                3.955224
6495                3.955224
9861                9.865672
1077                2.477612
2298                2.477612
10163               2.477612
620                 8.388060
11476               8.388060
3034                5.432836
7116                3.955224
4353                3.955224
7977                3.955224
5913                3.955224
34                  1.000000
2323                1.000000
696                 3.955224
10959               2.477612
2782                5.432836
8938                8.388060
3635                3.955224
5387                2.477612
7746                3.955224
10232               2.477612
665                 1.000000